#!/bin/bash
#
# Xtopod - One-Click Launcher for macOS
# Double-click this file to run the full podcast generation pipeline
#

# Change to the script's directory
cd "$(dirname "$0")"

echo "========================================"
echo "  X Digest - X to Podcast Pipeline"
echo "========================================"
echo ""

# Check for Python 3
if ! command -v python3 &> /dev/null; then
    echo "ERROR: Python 3 is not installed."
    echo ""
    echo "Opening Python download page..."
    open "https://www.python.org/downloads/"
    echo ""
    echo "Please install Python 3 and run this script again."
    read -p "Press Enter to exit..."
    exit 1
fi

# ============================================
# FIRST TIME SETUP - API Keys
# ============================================
if [ ! -f ".env" ]; then
    echo "First time setup detected! Let's get your API keys."
    echo ""
    echo "You'll need two API keys:"
    echo "  1. OpenRouter API key (for AI analysis)"
    echo "  2. Google API key (for text-to-speech)"
    echo ""
    read -p "Press Enter to continue with setup..."
    echo ""

    # --- OpenRouter API Key ---
    echo "========================================"
    echo "  Step 1: OpenRouter API Key"
    echo "========================================"
    echo ""
    echo "OpenRouter gives you access to Gemini and other AI models."
    echo "Opening OpenRouter in your browser..."
    echo ""
    open "https://openrouter.ai/keys"
    sleep 2
    echo "Instructions:"
    echo "  1. Sign up or log in to OpenRouter"
    echo "  2. Click 'Create Key'"
    echo "  3. Copy the key (starts with sk-or-v1-...)"
    echo ""
    read -p "Paste your OpenRouter API key here: " OPENROUTER_KEY
    echo ""

    if [ -z "$OPENROUTER_KEY" ]; then
        echo "No key entered. You can add it later to .env file."
        OPENROUTER_KEY="sk-or-v1-YOUR-KEY-HERE"
    fi

    # --- Google API Key ---
    echo "========================================"
    echo "  Step 2: Google API Key"
    echo "========================================"
    echo ""
    echo "Google API key is needed for Gemini text-to-speech."
    echo "Opening Google AI Studio in your browser..."
    echo ""
    open "https://aistudio.google.com/app/apikey"
    sleep 2
    echo "Instructions:"
    echo "  1. Sign in with your Google account"
    echo "  2. Click 'Create API Key'"
    echo "  3. Copy the key"
    echo ""
    read -p "Paste your Google API key here: " GOOGLE_KEY
    echo ""

    if [ -z "$GOOGLE_KEY" ]; then
        echo "No key entered. You can add it later to .env file."
        GOOGLE_KEY="YOUR-GOOGLE-KEY-HERE"
    fi

    # --- Create .env file ---
    echo "Creating .env configuration file..."
    cat > .env << EOF
# X Digest Configuration
# Generated by launch.command

# ===========================================
# LLM CONFIGURATION (OpenRouter)
# ===========================================
LLM_PROVIDER=openrouter
OPENROUTER_API_KEY=$OPENROUTER_KEY

# Model settings (Gemini 2.5 Flash via OpenRouter)
GEMINI_MODEL=google/gemini-2.5-flash-preview-09-2025
ANALYSIS_MODEL=google/gemini-2.5-flash-preview-09-2025
SCRIPT_MODEL=google/gemini-2.5-flash-preview-09-2025

# ===========================================
# TEXT-TO-SPEECH (Google Gemini)
# ===========================================
TTS_PROVIDER=gemini
GOOGLE_API_KEY=$GOOGLE_KEY

# ===========================================
# PODCAST SETTINGS
# ===========================================
PODCAST_NAME=X Digest
HOST1_NAME=Alex
HOST2_NAME=Jordan
HOST1_VOICE=Kore
HOST2_VOICE=Puck
TARGET_DURATION=15
MIN_INTEREST_SCORE=6.0
MAX_TOPICS=10
PODCAST_STYLE=casual

# ===========================================
# STORAGE & OUTPUT
# ===========================================
XTOPOD_DB_PATH=data/xtopod.db
OUTPUT_DIR=output
EOF

    echo ""
    echo "[OK] .env file created!"
    echo ""
fi

# ============================================
# FIRST TIME SETUP - X Cookies
# ============================================
if [ ! -f "cookies.json" ]; then
    echo "========================================"
    echo "  Step 3: X (Twitter) Cookies"
    echo "========================================"
    echo ""
    echo "To access your X feed, we need your browser cookies."
    echo ""
    echo "Opening X.com in your browser..."
    open "https://x.com"
    sleep 2
    echo ""
    echo "Instructions:"
    echo "  1. Make sure you're logged into X"
    echo "  2. Press Cmd+Option+I to open Developer Tools"
    echo "  3. Click 'Application' tab at the top"
    echo "  4. In left sidebar: Cookies > https://x.com"
    echo "  5. Find 'auth_token' - copy its Value"
    echo ""
    read -p "Paste your auth_token here: " AUTH_TOKEN
    echo ""
    echo "  6. Find 'ct0' - copy its Value"
    echo ""
    read -p "Paste your ct0 token here: " CT0_TOKEN
    echo ""

    if [ -z "$AUTH_TOKEN" ] || [ -z "$CT0_TOKEN" ]; then
        echo "ERROR: Both tokens are required!"
        echo "Please run this script again and enter both values."
        read -p "Press Enter to exit..."
        exit 1
    fi

    # Create cookies.json
    cat > cookies.json << EOF
[
  {
    "name": "auth_token",
    "value": "$AUTH_TOKEN",
    "domain": ".x.com",
    "path": "/"
  },
  {
    "name": "ct0",
    "value": "$CT0_TOKEN",
    "domain": ".x.com",
    "path": "/"
  }
]
EOF

    echo "[OK] cookies.json created!"
    echo ""
fi

echo "========================================"
echo "  Setup Complete! Starting X Digest..."
echo "========================================"
echo ""

# Create virtual environment if it doesn't exist
if [ ! -d ".venv" ]; then
    echo "Creating virtual environment..."
    python3 -m venv .venv
    echo ""
fi

# Activate virtual environment
source .venv/bin/activate

# Install/upgrade dependencies
echo "Installing dependencies (this may take a few minutes on first run)..."
pip install -q --upgrade pip
pip install -e . 2>&1 | tail -5
echo "[OK] Dependencies installed"
echo ""

# Always ensure Playwright browsers are installed
echo "Checking browser installation..."
echo "(First run downloads ~150MB - please wait)"
echo ""
playwright install chromium
echo ""
echo "[OK] Browser ready"

echo ""
echo "Starting X Digest Quick Mode..."
echo "========================================"
echo ""

# Run quick mode - collects, analyzes, and generates in one command
python3 -m src.cli quick --tweets 200

if [ $? -ne 0 ]; then
    echo ""
    echo "ERROR: Pipeline failed. Check the error message above."
    read -p "Press Enter to exit..."
    exit 1
fi

echo ""
read -p "Press Enter to exit..."
