@echo off
setlocal enabledelayedexpansion
REM Xtopod - One-Click Launcher for Windows
REM Double-click this file to run the full podcast generation pipeline

cd /d "%~dp0"

echo ========================================
echo   X Digest - X to Podcast Pipeline
echo ========================================
echo.

REM Check for Python
where python >nul 2>nul
if %ERRORLEVEL% neq 0 (
    echo ERROR: Python is not installed or not in PATH.
    echo.
    echo Opening Python download page...
    start https://www.python.org/downloads/
    echo.
    echo Please install Python 3 and check "Add Python to PATH"
    echo Then run this script again.
    pause
    exit /b 1
)

REM ============================================
REM FIRST TIME SETUP - API Keys
REM ============================================
if not exist ".env" (
    echo First time setup detected! Let's get your API keys.
    echo.
    echo You'll need two API keys:
    echo   1. OpenRouter API key ^(for AI analysis^)
    echo   2. Google API key ^(for text-to-speech^)
    echo.
    pause

    REM --- OpenRouter API Key ---
    echo.
    echo ========================================
    echo   Step 1: OpenRouter API Key
    echo ========================================
    echo.
    echo OpenRouter gives you access to Gemini and other AI models.
    echo Opening OpenRouter in your browser...
    echo.
    start https://openrouter.ai/keys
    timeout /t 3 >nul
    echo Instructions:
    echo   1. Sign up or log in to OpenRouter
    echo   2. Click 'Create Key'
    echo   3. Copy the key ^(starts with sk-or-v1-...^)
    echo.
    set /p OPENROUTER_KEY="Paste your OpenRouter API key here: "
    echo.

    if "!OPENROUTER_KEY!"=="" (
        echo No key entered. You can add it later to .env file.
        set OPENROUTER_KEY=sk-or-v1-YOUR-KEY-HERE
    )

    REM --- Google API Key ---
    echo ========================================
    echo   Step 2: Google API Key
    echo ========================================
    echo.
    echo Google API key is needed for Gemini text-to-speech.
    echo Opening Google AI Studio in your browser...
    echo.
    start https://aistudio.google.com/app/apikey
    timeout /t 3 >nul
    echo Instructions:
    echo   1. Sign in with your Google account
    echo   2. Click 'Create API Key'
    echo   3. Copy the key
    echo.
    set /p GOOGLE_KEY="Paste your Google API key here: "
    echo.

    if "!GOOGLE_KEY!"=="" (
        echo No key entered. You can add it later to .env file.
        set GOOGLE_KEY=YOUR-GOOGLE-KEY-HERE
    )

    REM --- Create .env file ---
    echo Creating .env configuration file...
    (
        echo # X Digest Configuration
        echo # Generated by launch.bat
        echo.
        echo # ===========================================
        echo # LLM CONFIGURATION ^(OpenRouter^)
        echo # ===========================================
        echo LLM_PROVIDER=openrouter
        echo OPENROUTER_API_KEY=!OPENROUTER_KEY!
        echo.
        echo # Model settings ^(Gemini 2.5 Flash via OpenRouter^)
        echo GEMINI_MODEL=google/gemini-2.5-flash-preview-09-2025
        echo ANALYSIS_MODEL=google/gemini-2.5-flash-preview-09-2025
        echo SCRIPT_MODEL=google/gemini-2.5-flash-preview-09-2025
        echo.
        echo # ===========================================
        echo # TEXT-TO-SPEECH ^(Google Gemini^)
        echo # ===========================================
        echo TTS_PROVIDER=gemini
        echo GOOGLE_API_KEY=!GOOGLE_KEY!
        echo.
        echo # ===========================================
        echo # PODCAST SETTINGS
        echo # ===========================================
        echo PODCAST_NAME=X Digest
        echo HOST1_NAME=Alex
        echo HOST2_NAME=Jordan
        echo HOST1_VOICE=Kore
        echo HOST2_VOICE=Puck
        echo TARGET_DURATION=15
        echo MIN_INTEREST_SCORE=6.0
        echo MAX_TOPICS=10
        echo PODCAST_STYLE=casual
        echo.
        echo # ===========================================
        echo # STORAGE ^& OUTPUT
        echo # ===========================================
        echo XTOPOD_DB_PATH=data/xtopod.db
        echo OUTPUT_DIR=output
    ) > .env

    echo.
    echo [OK] .env file created!
    echo.
)

REM ============================================
REM FIRST TIME SETUP - X Cookies
REM ============================================
if not exist "cookies.json" (
    echo ========================================
    echo   Step 3: X ^(Twitter^) Cookies
    echo ========================================
    echo.
    echo To access your X feed, we need your browser cookies.
    echo.
    echo Opening X.com in your browser...
    start https://x.com
    timeout /t 3 >nul
    echo.
    echo Instructions:
    echo   1. Make sure you're logged into X
    echo   2. Press F12 to open Developer Tools
    echo   3. Click 'Application' tab at the top
    echo   4. In left sidebar: Cookies ^> https://x.com
    echo   5. Find 'auth_token' - copy its Value
    echo.
    set /p AUTH_TOKEN="Paste your auth_token here: "
    echo.
    echo   6. Find 'ct0' - copy its Value
    echo.
    set /p CT0_TOKEN="Paste your ct0 token here: "
    echo.

    if "!AUTH_TOKEN!"=="" (
        echo ERROR: auth_token is required!
        echo Please run this script again and enter the value.
        pause
        exit /b 1
    )
    if "!CT0_TOKEN!"=="" (
        echo ERROR: ct0 token is required!
        echo Please run this script again and enter the value.
        pause
        exit /b 1
    )

    REM Create cookies.json
    (
        echo [
        echo   {
        echo     "name": "auth_token",
        echo     "value": "!AUTH_TOKEN!",
        echo     "domain": ".x.com",
        echo     "path": "/"
        echo   },
        echo   {
        echo     "name": "ct0",
        echo     "value": "!CT0_TOKEN!",
        echo     "domain": ".x.com",
        echo     "path": "/"
        echo   }
        echo ]
    ) > cookies.json

    echo [OK] cookies.json created!
    echo.
)

echo ========================================
echo   Setup Complete! Starting X Digest...
echo ========================================
echo.

REM Create virtual environment if it doesn't exist
if not exist ".venv" (
    echo Creating virtual environment...
    python -m venv .venv
    echo.
)

REM Activate virtual environment
call .venv\Scripts\activate.bat

REM Install/upgrade dependencies
echo Installing dependencies (this may take a few minutes on first run)...
pip install -q --upgrade pip
pip install -e . 2>&1
echo [OK] Dependencies installed
echo.

REM Always ensure Playwright browsers are installed
echo Checking browser installation...
echo (First run downloads ~150MB - please wait)
echo.
playwright install chromium
echo.
echo [OK] Browser ready

echo.
echo Starting X Digest Quick Mode...
echo ========================================
echo.

REM Run quick mode - collects, analyzes, and generates in one command
python -m src.cli quick --tweets 200

if %ERRORLEVEL% neq 0 (
    echo.
    echo ERROR: Pipeline failed. Check the error message above.
    pause
    exit /b 1
)

echo.
pause
